server_groups:
- css_class: group-isu
  name: ISU
  servers:
  - SRVISUASCS
  - SRVISUPRD
  - SRVISUPRDDB
- css_class: group-erp
  name: ERP
  servers:
  - SRVERPPRD
  - SRVSAPERPBDD
- css_class: group-solman
  name: SOLMAN
  servers:
  - SOLMANPRD
- css_class: group-bo
  name: BO
  servers:
  - SRVBOPRD
- css_class: group-bw
  name: BW
  servers:
  - SRVBWPRD
  - SRVSAPBWBDD
- css_class: group-crm
  name: CRM
  servers:
  - SRVCRMASCS
  - SRVCRMPRD
  - SRVCRMPRDDB
- css_class: group-dc
  name: Domain Controller
  servers:
  - SRVDCON4-(AD-DNS)
- css_class: group-mcf
  name: MCF
  servers:
  - SRVGTWPRDCS
  - SRVGTWPRDPAS
  - SRVMOBPRD
  - SRVHANDBPRD
- css_class: group-po
  name: PO
  servers:
  - SRVPOPRDCS - RESPALDO 2025-08-11
  - SRVPOPRDDB - RESPALDO 2025-08-11
  - SRVPOPRDPAS - RESPALDO 2025-08-11
- css_class: group-sao
  name: SAO
  servers:
  - SRVSAOBDD
  - SRVSAOPRD
- css_class: group-otros
  name: Otros
  servers:
  - DMZ-SRVSAPROU
  - DMZ-SRVWDPRD
  - SRVALMCS
  - SRVALMPRDN
  - SRVSTG (SRVALMPRD)
- css_class: group-bo
  name: POC - Real Server
  servers:
  - SRV-REAL-POC
  - SRV-CRM-POC
settings:
  refresh_interval_seconds: 30
  show_aws_errors: false
  version: v0.2.01
