name: Deploy Streamlit App to EC2

on:
  push:
    branches:
      - main # O la rama que uses para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2 via SSM
      run: |
        aws ssm send-command \
          --instance-ids $(aws ec2 describe-instances --filters "Name=tag:Name,Values=streamlit-dashboard" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text --region us-east-1) \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Streamlit app from GitHub Actions" \
          --parameters commands="'set -x &&           sudo mkdir -p /home/ec2-user/POC-Dashboard &&           sudo chown -R ec2-user:ec2-user /home/ec2-user/POC-Dashboard &&           cd /home/ec2-user/POC-Dashboard &&           sudo -u ec2-user git init &&           if ! sudo -u ec2-user git remote get-url origin > /dev/null 2>&1; then sudo -u ec2-user git remote add origin https://github.com/${{ github.repository }}; fi &&           sudo -u ec2-user git config pull.rebase false &&           sudo -u ec2-user git fetch origin main &&           sudo -u ec2-user git reset --hard origin/main &&           sudo -u ec2-user /usr/bin/python3.13 -m pip install -r requirements.txt &&           sudo systemctl restart ${{ secrets.STREAMLIT_SERVICE_NAME }}'" \
          --timeout-seconds 600 \
          --region us-east-1

    - name: Check SSM Command Status (Optional)
      run: |
        # This part is more complex to get the command ID and check status, 
        # but for now, we assume send-command succeeds if no error is returned.
        echo "SSM command sent. Check SSM Run Command history in AWS console for status."
