name: Deploy Streamlit App to EC2

on:
  push:
    branches:
      - main # O la rama que uses para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EC2 via SSM
      run: |
        aws ssm send-command 
          --instance-ids $(aws ec2 describe-instances --filters "Name=tag:Name,Values=streamlit-dashboard" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text --region us-east-1) 
          --document-name "AWS-RunShellScript" 
          --comment "Deploy Streamlit app from GitHub Actions" 
          --parameters commands="'set -x && cd ${{ secrets.APP_PATH }} && git config --global --add safe.directory ${{ secrets.APP_PATH }} && echo "Current directory: $(pwd)" && git pull origin main 2>&1 | tee /tmp/git_pull_output.log && echo "Git pull output:" && cat /tmp/git_pull_output.log && /usr/bin/python3.11 -m pip install -r requirements.txt && sudo systemctl restart ${{ secrets.STREAMLIT_SERVICE_NAME }} && sudo systemctl status ${{ secrets.STREAMLIT_SERVICE_NAME }}'" \
          --timeout-seconds 600 \
          --region us-east-1

    - name: Check SSM Command Status (Optional)
      run: |
        # This part is more complex to get the command ID and check status, 
        # but for now, we assume send-command succeeds if no error is returned.
        echo "SSM command sent. Check SSM Run Command history in AWS console for status."
